version: "3"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-container
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
